// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_S5ClientPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5ClientPtr;

  @protected
  S5Client
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          dynamic raw);

  @protected
  S5Client
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          dynamic raw);

  @protected
  S5Client
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  DirectoryListing dco_decode_directory_listing(dynamic raw);

  @protected
  FileEntry dco_decode_file_entry(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FileEntry> dco_decode_list_file_entry(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  S5Error dco_decode_s_5_error(dynamic raw);

  @protected
  S5Keys dco_decode_s_5_keys(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  S5Client
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          SseDeserializer deserializer);

  @protected
  S5Client
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          SseDeserializer deserializer);

  @protected
  S5Client
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  DirectoryListing sse_decode_directory_listing(SseDeserializer deserializer);

  @protected
  FileEntry sse_decode_file_entry(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FileEntry> sse_decode_list_file_entry(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  S5Error sse_decode_s_5_error(SseDeserializer deserializer);

  @protected
  S5Keys sse_decode_s_5_keys(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<ffi.Uint32> cst_encode_box_autoadd_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_u_32(cst_encode_u_32(raw));
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_file_entry> cst_encode_list_file_entry(
      List<FileEntry> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_file_entry(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_file_entry(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_encode_list_prim_u_8_loose(
      List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
      Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
      String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<ffi.Uint32> cst_encode_opt_box_autoadd_u_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_u_32(raw);
  }

  @protected
  int cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_directory_listing(
      DirectoryListing apiObj, wire_cst_directory_listing wireObj) {
    wireObj.files = cst_encode_list_file_entry(apiObj.files);
    wireObj.directories = cst_encode_list_String(apiObj.directories);
  }

  @protected
  void cst_api_fill_to_wire_file_entry(
      FileEntry apiObj, wire_cst_file_entry wireObj) {
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.file_ref_json = cst_encode_String(apiObj.fileRefJson);
    wireObj.size = cst_encode_u_64(apiObj.size);
    wireObj.media_type = cst_encode_opt_String(apiObj.mediaType);
    wireObj.timestamp = cst_encode_opt_box_autoadd_u_32(apiObj.timestamp);
  }

  @protected
  void cst_api_fill_to_wire_s_5_error(
      S5Error apiObj, wire_cst_s_5_error wireObj) {
    if (apiObj is S5Error_InvalidInput) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 0;
      wireObj.kind.InvalidInput.field0 = pre_field0;
      return;
    }
    if (apiObj is S5Error_ConnectionError) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 1;
      wireObj.kind.ConnectionError.field0 = pre_field0;
      return;
    }
    if (apiObj is S5Error_StorageError) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 2;
      wireObj.kind.StorageError.field0 = pre_field0;
      return;
    }
    if (apiObj is S5Error_FileNotFound) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 3;
      wireObj.kind.FileNotFound.field0 = pre_field0;
      return;
    }
    if (apiObj is S5Error_CryptoError) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 4;
      wireObj.kind.CryptoError.field0 = pre_field0;
      return;
    }
    if (apiObj is S5Error_InternalError) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 5;
      wireObj.kind.InternalError.field0 = pre_field0;
      return;
    }
  }

  @protected
  void cst_api_fill_to_wire_s_5_keys(S5Keys apiObj, wire_cst_s_5_keys wireObj) {
    wireObj.root_secret_hex = cst_encode_String(apiObj.rootSecretHex);
    wireObj.public_key_hex = cst_encode_String(apiObj.publicKeyHex);
    wireObj.encryption_key_hex = cst_encode_String(apiObj.encryptionKeyHex);
    wireObj.signing_key_hex = cst_encode_String(apiObj.signingKeyHex);
    wireObj.iroh_secret_key_hex = cst_encode_String(apiObj.irohSecretKeyHex);
  }

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
      S5Client raw);

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
      S5Client raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
      S5Client raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          S5Client self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          S5Client self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          S5Client self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_directory_listing(
      DirectoryListing self, SseSerializer serializer);

  @protected
  void sse_encode_file_entry(FileEntry self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_file_entry(
      List<FileEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_s_5_error(S5Error self, SseSerializer serializer);

  @protected
  void sse_encode_s_5_keys(S5Keys self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(int ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
    'store_dart_post_cobject',
  );
  late final _store_dart_post_cobject =
      _store_dart_post_cobjectPtr.asFunction<void Function(int)>();

  void wire__crate__api__S5Client_connect(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> seed_phrase,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> remote_node_id,
  ) {
    return _wire__crate__api__S5Client_connect(
      port_,
      seed_phrase,
      remote_node_id,
    );
  }

  late final _wire__crate__api__S5Client_connectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_s5_flutter_wire__crate__api__S5Client_connect');
  late final _wire__crate__api__S5Client_connect =
      _wire__crate__api__S5Client_connectPtr.asFunction<
          void Function(
            int,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  void wire__crate__api__S5Client_create_directory(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> path,
  ) {
    return _wire__crate__api__S5Client_create_directory(port_, that, path);
  }

  late final _wire__crate__api__S5Client_create_directoryPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_s5_flutter_wire__crate__api__S5Client_create_directory');
  late final _wire__crate__api__S5Client_create_directory =
      _wire__crate__api__S5Client_create_directoryPtr.asFunction<
          void Function(
              int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__S5Client_delete_file(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> path,
  ) {
    return _wire__crate__api__S5Client_delete_file(port_, that, path);
  }

  late final _wire__crate__api__S5Client_delete_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_s5_flutter_wire__crate__api__S5Client_delete_file');
  late final _wire__crate__api__S5Client_delete_file =
      _wire__crate__api__S5Client_delete_filePtr.asFunction<
          void Function(
              int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__S5Client_disconnect(int port_, int that) {
    return _wire__crate__api__S5Client_disconnect(port_, that);
  }

  late final _wire__crate__api__S5Client_disconnectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
    'frbgen_s5_flutter_wire__crate__api__S5Client_disconnect',
  );
  late final _wire__crate__api__S5Client_disconnect =
      _wire__crate__api__S5Client_disconnectPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__S5Client_download_blob(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> hash_hex,
  ) {
    return _wire__crate__api__S5Client_download_blob(port_, that, hash_hex);
  }

  late final _wire__crate__api__S5Client_download_blobPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_s5_flutter_wire__crate__api__S5Client_download_blob');
  late final _wire__crate__api__S5Client_download_blob =
      _wire__crate__api__S5Client_download_blobPtr.asFunction<
          void Function(
              int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__S5Client_download_file(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> path,
  ) {
    return _wire__crate__api__S5Client_download_file(port_, that, path);
  }

  late final _wire__crate__api__S5Client_download_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_s5_flutter_wire__crate__api__S5Client_download_file');
  late final _wire__crate__api__S5Client_download_file =
      _wire__crate__api__S5Client_download_filePtr.asFunction<
          void Function(
              int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__S5Client_file_exists(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> path,
  ) {
    return _wire__crate__api__S5Client_file_exists(port_, that, path);
  }

  late final _wire__crate__api__S5Client_file_existsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_s5_flutter_wire__crate__api__S5Client_file_exists');
  late final _wire__crate__api__S5Client_file_exists =
      _wire__crate__api__S5Client_file_existsPtr.asFunction<
          void Function(
              int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__S5Client_file_get(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> path,
  ) {
    return _wire__crate__api__S5Client_file_get(port_, that, path);
  }

  late final _wire__crate__api__S5Client_file_getPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_s5_flutter_wire__crate__api__S5Client_file_get');
  late final _wire__crate__api__S5Client_file_get =
      _wire__crate__api__S5Client_file_getPtr.asFunction<
          void Function(
              int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__S5Client_is_connected(int port_, int that) {
    return _wire__crate__api__S5Client_is_connected(port_, that);
  }

  late final _wire__crate__api__S5Client_is_connectedPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
    'frbgen_s5_flutter_wire__crate__api__S5Client_is_connected',
  );
  late final _wire__crate__api__S5Client_is_connected =
      _wire__crate__api__S5Client_is_connectedPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__S5Client_list_directory(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> path,
  ) {
    return _wire__crate__api__S5Client_list_directory(port_, that, path);
  }

  late final _wire__crate__api__S5Client_list_directoryPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_s5_flutter_wire__crate__api__S5Client_list_directory');
  late final _wire__crate__api__S5Client_list_directory =
      _wire__crate__api__S5Client_list_directoryPtr.asFunction<
          void Function(
              int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  WireSyncRust2DartDco wire__crate__api__S5Client_node_id(int that) {
    return _wire__crate__api__S5Client_node_id(that);
  }

  late final _wire__crate__api__S5Client_node_idPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
    'frbgen_s5_flutter_wire__crate__api__S5Client_node_id',
  );
  late final _wire__crate__api__S5Client_node_id =
      _wire__crate__api__S5Client_node_idPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco wire__crate__api__S5Client_public_key(int that) {
    return _wire__crate__api__S5Client_public_key(that);
  }

  late final _wire__crate__api__S5Client_public_keyPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
    'frbgen_s5_flutter_wire__crate__api__S5Client_public_key',
  );
  late final _wire__crate__api__S5Client_public_key =
      _wire__crate__api__S5Client_public_keyPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  void wire__crate__api__S5Client_test_connection(int port_, int that) {
    return _wire__crate__api__S5Client_test_connection(port_, that);
  }

  late final _wire__crate__api__S5Client_test_connectionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
    'frbgen_s5_flutter_wire__crate__api__S5Client_test_connection',
  );
  late final _wire__crate__api__S5Client_test_connection =
      _wire__crate__api__S5Client_test_connectionPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__S5Client_upload_file(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> path,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> filename,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> content,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> media_type,
  ) {
    return _wire__crate__api__S5Client_upload_file(
      port_,
      that,
      path,
      filename,
      content,
      media_type,
    );
  }

  late final _wire__crate__api__S5Client_upload_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_s5_flutter_wire__crate__api__S5Client_upload_file');
  late final _wire__crate__api__S5Client_upload_file =
      _wire__crate__api__S5Client_upload_filePtr.asFunction<
          void Function(
            int,
            int,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__decrypt_chunk_xchacha20poly1305(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> key,
    int chunk_index,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> ciphertext,
  ) {
    return _wire__crate__api__decrypt_chunk_xchacha20poly1305(
      key,
      chunk_index,
      ciphertext,
    );
  }

  late final _wire__crate__api__decrypt_chunk_xchacha20poly1305Ptr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(
                ffi.Pointer<wire_cst_list_prim_u_8_loose>,
                ffi.Uint64,
                ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              )>>(
      'frbgen_s5_flutter_wire__crate__api__decrypt_chunk_xchacha20poly1305');
  late final _wire__crate__api__decrypt_chunk_xchacha20poly1305 =
      _wire__crate__api__decrypt_chunk_xchacha20poly1305Ptr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            int,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )>();

  WireSyncRust2DartDco wire__crate__api__decrypt_xchacha20poly1305(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> key,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> data,
  ) {
    return _wire__crate__api__decrypt_xchacha20poly1305(key, data);
  }

  late final _wire__crate__api__decrypt_xchacha20poly1305Ptr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )>>('frbgen_s5_flutter_wire__crate__api__decrypt_xchacha20poly1305');
  late final _wire__crate__api__decrypt_xchacha20poly1305 =
      _wire__crate__api__decrypt_xchacha20poly1305Ptr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )>();

  WireSyncRust2DartDco wire__crate__api__derive_keys(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> phrase,
  ) {
    return _wire__crate__api__derive_keys(phrase);
  }

  late final _wire__crate__api__derive_keysPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_s5_flutter_wire__crate__api__derive_keys');
  late final _wire__crate__api__derive_keys =
      _wire__crate__api__derive_keysPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__encrypt_xchacha20poly1305(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> key,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> plaintext,
  ) {
    return _wire__crate__api__encrypt_xchacha20poly1305(key, plaintext);
  }

  late final _wire__crate__api__encrypt_xchacha20poly1305Ptr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )>>('frbgen_s5_flutter_wire__crate__api__encrypt_xchacha20poly1305');
  late final _wire__crate__api__encrypt_xchacha20poly1305 =
      _wire__crate__api__encrypt_xchacha20poly1305Ptr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )>();

  WireSyncRust2DartDco wire__crate__api__generate_seed_phrase() {
    return _wire__crate__api__generate_seed_phrase();
  }

  late final _wire__crate__api__generate_seed_phrasePtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
    'frbgen_s5_flutter_wire__crate__api__generate_seed_phrase',
  );
  late final _wire__crate__api__generate_seed_phrase =
      _wire__crate__api__generate_seed_phrasePtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__hash_blake3(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> data,
  ) {
    return _wire__crate__api__hash_blake3(data);
  }

  late final _wire__crate__api__hash_blake3Ptr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )>>('frbgen_s5_flutter_wire__crate__api__hash_blake3');
  late final _wire__crate__api__hash_blake3 =
      _wire__crate__api__hash_blake3Ptr.asFunction<
          WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>)>();

  WireSyncRust2DartDco wire__crate__api__validate_seed_phrase(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> phrase,
  ) {
    return _wire__crate__api__validate_seed_phrase(phrase);
  }

  late final _wire__crate__api__validate_seed_phrasePtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_s5_flutter_wire__crate__api__validate_seed_phrase');
  late final _wire__crate__api__validate_seed_phrase =
      _wire__crate__api__validate_seed_phrasePtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5ClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
    'frbgen_s5_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client',
  );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5ClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5ClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
    'frbgen_s5_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client',
  );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5ClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Uint32> cst_new_box_autoadd_u_32(int value) {
    return _cst_new_box_autoadd_u_32(value);
  }

  late final _cst_new_box_autoadd_u_32Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Uint32> Function(ffi.Uint32)>>(
    'frbgen_s5_flutter_cst_new_box_autoadd_u_32',
  );
  late final _cst_new_box_autoadd_u_32 = _cst_new_box_autoadd_u_32Ptr
      .asFunction<ffi.Pointer<ffi.Uint32> Function(int)>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(int len) {
    return _cst_new_list_String(len);
  }

  late final _cst_new_list_StringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_String> Function(
              ffi.Int32)>>('frbgen_s5_flutter_cst_new_list_String');
  late final _cst_new_list_String = _cst_new_list_StringPtr
      .asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_file_entry> cst_new_list_file_entry(int len) {
    return _cst_new_list_file_entry(len);
  }

  late final _cst_new_list_file_entryPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_file_entry> Function(
              ffi.Int32)>>('frbgen_s5_flutter_cst_new_list_file_entry');
  late final _cst_new_list_file_entry = _cst_new_list_file_entryPtr
      .asFunction<ffi.Pointer<wire_cst_list_file_entry> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_new_list_prim_u_8_loose(
    int len,
  ) {
    return _cst_new_list_prim_u_8_loose(len);
  }

  late final _cst_new_list_prim_u_8_loosePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(
              ffi.Int32)>>('frbgen_s5_flutter_cst_new_list_prim_u_8_loose');
  late final _cst_new_list_prim_u_8_loose = _cst_new_list_prim_u_8_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(
              ffi.Int32)>>('frbgen_s5_flutter_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
    'dummy_method_to_enforce_bundling',
  );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_u_8_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_file_entry extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> file_ref_json;

  @ffi.Uint64()
  external int size;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> media_type;

  external ffi.Pointer<ffi.Uint32> timestamp;
}

final class wire_cst_list_file_entry extends ffi.Struct {
  external ffi.Pointer<wire_cst_file_entry> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_directory_listing extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_file_entry> files;

  external ffi.Pointer<wire_cst_list_String> directories;
}

final class wire_cst_S5Error_InvalidInput extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field0;
}

final class wire_cst_S5Error_ConnectionError extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field0;
}

final class wire_cst_S5Error_StorageError extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field0;
}

final class wire_cst_S5Error_FileNotFound extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field0;
}

final class wire_cst_S5Error_CryptoError extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field0;
}

final class wire_cst_S5Error_InternalError extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field0;
}

final class S5ErrorKind extends ffi.Union {
  external wire_cst_S5Error_InvalidInput InvalidInput;

  external wire_cst_S5Error_ConnectionError ConnectionError;

  external wire_cst_S5Error_StorageError StorageError;

  external wire_cst_S5Error_FileNotFound FileNotFound;

  external wire_cst_S5Error_CryptoError CryptoError;

  external wire_cst_S5Error_InternalError InternalError;
}

final class wire_cst_s_5_error extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external S5ErrorKind kind;
}

final class wire_cst_s_5_keys extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> root_secret_hex;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key_hex;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> encryption_key_hex;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> signing_key_hex;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> iroh_secret_key_hex;
}
