// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_S5ClientPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client;

  @protected
  S5Client
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          dynamic raw);

  @protected
  S5Client
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          dynamic raw);

  @protected
  S5Client
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  DirectoryListing dco_decode_directory_listing(dynamic raw);

  @protected
  FileEntry dco_decode_file_entry(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FileEntry> dco_decode_list_file_entry(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  S5Error dco_decode_s_5_error(dynamic raw);

  @protected
  S5Keys dco_decode_s_5_keys(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  S5Client
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          SseDeserializer deserializer);

  @protected
  S5Client
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          SseDeserializer deserializer);

  @protected
  S5Client
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  DirectoryListing sse_decode_directory_listing(SseDeserializer deserializer);

  @protected
  FileEntry sse_decode_file_entry(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FileEntry> sse_decode_list_file_entry(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  S5Error sse_decode_s_5_error(SseDeserializer deserializer);

  @protected
  S5Keys sse_decode_s_5_keys(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_box_autoadd_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_32(raw);
  }

  @protected
  JSAny cst_encode_directory_listing(DirectoryListing raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_file_entry(raw.files),
      cst_encode_list_String(raw.directories)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_file_entry(FileEntry raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.name),
      cst_encode_String(raw.fileRefJson),
      cst_encode_u_64(raw.size),
      cst_encode_opt_String(raw.mediaType),
      cst_encode_opt_box_autoadd_u_32(raw.timestamp)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_file_entry(List<FileEntry> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_file_entry).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_loose(List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_u_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_32(raw);
  }

  @protected
  JSAny cst_encode_s_5_error(S5Error raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is S5Error_InvalidInput) {
      return [0, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is S5Error_ConnectionError) {
      return [1, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is S5Error_StorageError) {
      return [2, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is S5Error_FileNotFound) {
      return [3, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is S5Error_CryptoError) {
      return [4, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is S5Error_InternalError) {
      return [5, cst_encode_String(raw.field0)].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny cst_encode_s_5_keys(S5Keys raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.rootSecretHex),
      cst_encode_String(raw.publicKeyHex),
      cst_encode_String(raw.encryptionKeyHex),
      cst_encode_String(raw.signingKeyHex),
      cst_encode_String(raw.irohSecretKeyHex)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
      S5Client raw);

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
      S5Client raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
      S5Client raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          S5Client self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          S5Client self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          S5Client self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_directory_listing(
      DirectoryListing self, SseSerializer serializer);

  @protected
  void sse_encode_file_entry(FileEntry self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_file_entry(
      List<FileEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_s_5_error(S5Error self, SseSerializer serializer);

  @protected
  void sse_encode_s_5_keys(S5Keys self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__S5Client_connect(
          NativePortType port_, String seed_phrase, String remote_node_id) =>
      wasmModule.wire__crate__api__S5Client_connect(
          port_, seed_phrase, remote_node_id);

  void wire__crate__api__S5Client_create_directory(
          NativePortType port_, int that, String path) =>
      wasmModule.wire__crate__api__S5Client_create_directory(port_, that, path);

  void wire__crate__api__S5Client_delete_file(
          NativePortType port_, int that, String path) =>
      wasmModule.wire__crate__api__S5Client_delete_file(port_, that, path);

  void wire__crate__api__S5Client_disconnect(NativePortType port_, int that) =>
      wasmModule.wire__crate__api__S5Client_disconnect(port_, that);

  void wire__crate__api__S5Client_download_blob(
          NativePortType port_, int that, String hash_hex) =>
      wasmModule.wire__crate__api__S5Client_download_blob(
          port_, that, hash_hex);

  void wire__crate__api__S5Client_download_file(
          NativePortType port_, int that, String path) =>
      wasmModule.wire__crate__api__S5Client_download_file(port_, that, path);

  void wire__crate__api__S5Client_file_exists(
          NativePortType port_, int that, String path) =>
      wasmModule.wire__crate__api__S5Client_file_exists(port_, that, path);

  void wire__crate__api__S5Client_file_get(
          NativePortType port_, int that, String path) =>
      wasmModule.wire__crate__api__S5Client_file_get(port_, that, path);

  void wire__crate__api__S5Client_is_connected(
          NativePortType port_, int that) =>
      wasmModule.wire__crate__api__S5Client_is_connected(port_, that);

  void wire__crate__api__S5Client_list_directory(
          NativePortType port_, int that, String path) =>
      wasmModule.wire__crate__api__S5Client_list_directory(port_, that, path);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__S5Client_node_id(int that) =>
          wasmModule.wire__crate__api__S5Client_node_id(that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__S5Client_public_key(int that) =>
          wasmModule.wire__crate__api__S5Client_public_key(that);

  void wire__crate__api__S5Client_test_connection(
          NativePortType port_, int that) =>
      wasmModule.wire__crate__api__S5Client_test_connection(port_, that);

  void wire__crate__api__S5Client_upload_file(NativePortType port_, int that,
          String path, String filename, JSAny content, String media_type) =>
      wasmModule.wire__crate__api__S5Client_upload_file(
          port_, that, path, filename, content, media_type);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__decrypt_chunk_xchacha20poly1305(
              JSAny key, JSAny chunk_index, JSAny ciphertext) =>
          wasmModule.wire__crate__api__decrypt_chunk_xchacha20poly1305(
              key, chunk_index, ciphertext);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__decrypt_xchacha20poly1305(JSAny key, JSAny data) =>
          wasmModule.wire__crate__api__decrypt_xchacha20poly1305(key, data);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__derive_keys(String phrase) =>
          wasmModule.wire__crate__api__derive_keys(phrase);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__encrypt_xchacha20poly1305(JSAny key, JSAny plaintext) =>
          wasmModule.wire__crate__api__encrypt_xchacha20poly1305(
              key, plaintext);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__generate_seed_phrase() =>
          wasmModule.wire__crate__api__generate_seed_phrase();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hash_blake3(JSAny data) =>
          wasmModule.wire__crate__api__hash_blake3(data);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__validate_seed_phrase(String phrase) =>
          wasmModule.wire__crate__api__validate_seed_phrase(phrase);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__S5Client_connect(
      NativePortType port_, String seed_phrase, String remote_node_id);

  external void wire__crate__api__S5Client_create_directory(
      NativePortType port_, int that, String path);

  external void wire__crate__api__S5Client_delete_file(
      NativePortType port_, int that, String path);

  external void wire__crate__api__S5Client_disconnect(
      NativePortType port_, int that);

  external void wire__crate__api__S5Client_download_blob(
      NativePortType port_, int that, String hash_hex);

  external void wire__crate__api__S5Client_download_file(
      NativePortType port_, int that, String path);

  external void wire__crate__api__S5Client_file_exists(
      NativePortType port_, int that, String path);

  external void wire__crate__api__S5Client_file_get(
      NativePortType port_, int that, String path);

  external void wire__crate__api__S5Client_is_connected(
      NativePortType port_, int that);

  external void wire__crate__api__S5Client_list_directory(
      NativePortType port_, int that, String path);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__S5Client_node_id(int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__S5Client_public_key(int that);

  external void wire__crate__api__S5Client_test_connection(
      NativePortType port_, int that);

  external void wire__crate__api__S5Client_upload_file(NativePortType port_,
      int that, String path, String filename, JSAny content, String media_type);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__decrypt_chunk_xchacha20poly1305(
          JSAny key, JSAny chunk_index, JSAny ciphertext);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__decrypt_xchacha20poly1305(JSAny key, JSAny data);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__derive_keys(String phrase);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__encrypt_xchacha20poly1305(JSAny key, JSAny plaintext);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__generate_seed_phrase();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hash_blake3(JSAny data);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__validate_seed_phrase(String phrase);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          int ptr);
}
