// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1770149007;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 's5_flutter',
    ioDirectory: 'target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<S5Client> crateApiS5ClientConnect(
      {required String seedPhrase, required String remoteNodeId});

  Future<void> crateApiS5ClientCreateDirectory(
      {required S5Client that, required String path});

  Future<void> crateApiS5ClientDeleteFile(
      {required S5Client that, required String path});

  Future<void> crateApiS5ClientDisconnect({required S5Client that});

  Future<Uint8List> crateApiS5ClientDownloadBlob(
      {required S5Client that, required String hashHex});

  Future<Uint8List> crateApiS5ClientDownloadFile(
      {required S5Client that, required String path});

  Future<bool> crateApiS5ClientFileExists(
      {required S5Client that, required String path});

  Future<String?> crateApiS5ClientFileGet(
      {required S5Client that, required String path});

  Future<bool> crateApiS5ClientIsConnected({required S5Client that});

  Future<DirectoryListing> crateApiS5ClientListDirectory(
      {required S5Client that, required String path});

  String crateApiS5ClientNodeId({required S5Client that});

  String crateApiS5ClientPublicKey({required S5Client that});

  Future<String> crateApiS5ClientTestConnection({required S5Client that});

  Future<String> crateApiS5ClientUploadFile(
      {required S5Client that,
      required String path,
      required String filename,
      required List<int> content,
      required String mediaType});

  Uint8List crateApiDecryptChunkXchacha20Poly1305(
      {required List<int> key,
      required BigInt chunkIndex,
      required List<int> ciphertext});

  Uint8List crateApiDecryptXchacha20Poly1305(
      {required List<int> key, required List<int> data});

  S5Keys crateApiDeriveKeys({required String phrase});

  Uint8List crateApiEncryptXchacha20Poly1305(
      {required List<int> key, required List<int> plaintext});

  String crateApiGenerateSeedPhrase();

  Uint8List crateApiHashBlake3({required List<int> data});

  bool crateApiValidateSeedPhrase({required String phrase});

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_S5Client;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_S5Client;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_S5ClientPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<S5Client> crateApiS5ClientConnect(
      {required String seedPhrase, required String remoteNodeId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(seedPhrase);
        var arg1 = cst_encode_String(remoteNodeId);
        return wire.wire__crate__api__S5Client_connect(port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData:
            dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client,
        decodeErrorData: dco_decode_s_5_error,
      ),
      constMeta: kCrateApiS5ClientConnectConstMeta,
      argValues: [seedPhrase, remoteNodeId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiS5ClientConnectConstMeta => const TaskConstMeta(
        debugName: "S5Client_connect",
        argNames: ["seedPhrase", "remoteNodeId"],
      );

  @override
  Future<void> crateApiS5ClientCreateDirectory(
      {required S5Client that, required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
                that);
        var arg1 = cst_encode_String(path);
        return wire.wire__crate__api__S5Client_create_directory(
            port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_s_5_error,
      ),
      constMeta: kCrateApiS5ClientCreateDirectoryConstMeta,
      argValues: [that, path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiS5ClientCreateDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "S5Client_create_directory",
        argNames: ["that", "path"],
      );

  @override
  Future<void> crateApiS5ClientDeleteFile(
      {required S5Client that, required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
                that);
        var arg1 = cst_encode_String(path);
        return wire.wire__crate__api__S5Client_delete_file(port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_s_5_error,
      ),
      constMeta: kCrateApiS5ClientDeleteFileConstMeta,
      argValues: [that, path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiS5ClientDeleteFileConstMeta => const TaskConstMeta(
        debugName: "S5Client_delete_file",
        argNames: ["that", "path"],
      );

  @override
  Future<void> crateApiS5ClientDisconnect({required S5Client that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
                that);
        return wire.wire__crate__api__S5Client_disconnect(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_s_5_error,
      ),
      constMeta: kCrateApiS5ClientDisconnectConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiS5ClientDisconnectConstMeta => const TaskConstMeta(
        debugName: "S5Client_disconnect",
        argNames: ["that"],
      );

  @override
  Future<Uint8List> crateApiS5ClientDownloadBlob(
      {required S5Client that, required String hashHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
                that);
        var arg1 = cst_encode_String(hashHex);
        return wire.wire__crate__api__S5Client_download_blob(port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_prim_u_8_strict,
        decodeErrorData: dco_decode_s_5_error,
      ),
      constMeta: kCrateApiS5ClientDownloadBlobConstMeta,
      argValues: [that, hashHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiS5ClientDownloadBlobConstMeta =>
      const TaskConstMeta(
        debugName: "S5Client_download_blob",
        argNames: ["that", "hashHex"],
      );

  @override
  Future<Uint8List> crateApiS5ClientDownloadFile(
      {required S5Client that, required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
                that);
        var arg1 = cst_encode_String(path);
        return wire.wire__crate__api__S5Client_download_file(port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_prim_u_8_strict,
        decodeErrorData: dco_decode_s_5_error,
      ),
      constMeta: kCrateApiS5ClientDownloadFileConstMeta,
      argValues: [that, path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiS5ClientDownloadFileConstMeta =>
      const TaskConstMeta(
        debugName: "S5Client_download_file",
        argNames: ["that", "path"],
      );

  @override
  Future<bool> crateApiS5ClientFileExists(
      {required S5Client that, required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
                that);
        var arg1 = cst_encode_String(path);
        return wire.wire__crate__api__S5Client_file_exists(port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: dco_decode_s_5_error,
      ),
      constMeta: kCrateApiS5ClientFileExistsConstMeta,
      argValues: [that, path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiS5ClientFileExistsConstMeta => const TaskConstMeta(
        debugName: "S5Client_file_exists",
        argNames: ["that", "path"],
      );

  @override
  Future<String?> crateApiS5ClientFileGet(
      {required S5Client that, required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
                that);
        var arg1 = cst_encode_String(path);
        return wire.wire__crate__api__S5Client_file_get(port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_opt_String,
        decodeErrorData: dco_decode_s_5_error,
      ),
      constMeta: kCrateApiS5ClientFileGetConstMeta,
      argValues: [that, path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiS5ClientFileGetConstMeta => const TaskConstMeta(
        debugName: "S5Client_file_get",
        argNames: ["that", "path"],
      );

  @override
  Future<bool> crateApiS5ClientIsConnected({required S5Client that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
                that);
        return wire.wire__crate__api__S5Client_is_connected(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiS5ClientIsConnectedConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiS5ClientIsConnectedConstMeta =>
      const TaskConstMeta(
        debugName: "S5Client_is_connected",
        argNames: ["that"],
      );

  @override
  Future<DirectoryListing> crateApiS5ClientListDirectory(
      {required S5Client that, required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
                that);
        var arg1 = cst_encode_String(path);
        return wire.wire__crate__api__S5Client_list_directory(
            port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_directory_listing,
        decodeErrorData: dco_decode_s_5_error,
      ),
      constMeta: kCrateApiS5ClientListDirectoryConstMeta,
      argValues: [that, path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiS5ClientListDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "S5Client_list_directory",
        argNames: ["that", "path"],
      );

  @override
  String crateApiS5ClientNodeId({required S5Client that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
                that);
        return wire.wire__crate__api__S5Client_node_id(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiS5ClientNodeIdConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiS5ClientNodeIdConstMeta => const TaskConstMeta(
        debugName: "S5Client_node_id",
        argNames: ["that"],
      );

  @override
  String crateApiS5ClientPublicKey({required S5Client that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
                that);
        return wire.wire__crate__api__S5Client_public_key(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiS5ClientPublicKeyConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiS5ClientPublicKeyConstMeta => const TaskConstMeta(
        debugName: "S5Client_public_key",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiS5ClientTestConnection({required S5Client that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
                that);
        return wire.wire__crate__api__S5Client_test_connection(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_s_5_error,
      ),
      constMeta: kCrateApiS5ClientTestConnectionConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiS5ClientTestConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "S5Client_test_connection",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiS5ClientUploadFile(
      {required S5Client that,
      required String path,
      required String filename,
      required List<int> content,
      required String mediaType}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
                that);
        var arg1 = cst_encode_String(path);
        var arg2 = cst_encode_String(filename);
        var arg3 = cst_encode_list_prim_u_8_loose(content);
        var arg4 = cst_encode_String(mediaType);
        return wire.wire__crate__api__S5Client_upload_file(
            port_, arg0, arg1, arg2, arg3, arg4);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_s_5_error,
      ),
      constMeta: kCrateApiS5ClientUploadFileConstMeta,
      argValues: [that, path, filename, content, mediaType],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiS5ClientUploadFileConstMeta => const TaskConstMeta(
        debugName: "S5Client_upload_file",
        argNames: ["that", "path", "filename", "content", "mediaType"],
      );

  @override
  Uint8List crateApiDecryptChunkXchacha20Poly1305(
      {required List<int> key,
      required BigInt chunkIndex,
      required List<int> ciphertext}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        var arg0 = cst_encode_list_prim_u_8_loose(key);
        var arg1 = cst_encode_u_64(chunkIndex);
        var arg2 = cst_encode_list_prim_u_8_loose(ciphertext);
        return wire.wire__crate__api__decrypt_chunk_xchacha20poly1305(
            arg0, arg1, arg2);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_prim_u_8_strict,
        decodeErrorData: dco_decode_s_5_error,
      ),
      constMeta: kCrateApiDecryptChunkXchacha20Poly1305ConstMeta,
      argValues: [key, chunkIndex, ciphertext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDecryptChunkXchacha20Poly1305ConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_chunk_xchacha20poly1305",
        argNames: ["key", "chunkIndex", "ciphertext"],
      );

  @override
  Uint8List crateApiDecryptXchacha20Poly1305(
      {required List<int> key, required List<int> data}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        var arg0 = cst_encode_list_prim_u_8_loose(key);
        var arg1 = cst_encode_list_prim_u_8_loose(data);
        return wire.wire__crate__api__decrypt_xchacha20poly1305(arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_prim_u_8_strict,
        decodeErrorData: dco_decode_s_5_error,
      ),
      constMeta: kCrateApiDecryptXchacha20Poly1305ConstMeta,
      argValues: [key, data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDecryptXchacha20Poly1305ConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_xchacha20poly1305",
        argNames: ["key", "data"],
      );

  @override
  S5Keys crateApiDeriveKeys({required String phrase}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        var arg0 = cst_encode_String(phrase);
        return wire.wire__crate__api__derive_keys(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_s_5_keys,
        decodeErrorData: dco_decode_s_5_error,
      ),
      constMeta: kCrateApiDeriveKeysConstMeta,
      argValues: [phrase],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeriveKeysConstMeta => const TaskConstMeta(
        debugName: "derive_keys",
        argNames: ["phrase"],
      );

  @override
  Uint8List crateApiEncryptXchacha20Poly1305(
      {required List<int> key, required List<int> plaintext}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        var arg0 = cst_encode_list_prim_u_8_loose(key);
        var arg1 = cst_encode_list_prim_u_8_loose(plaintext);
        return wire.wire__crate__api__encrypt_xchacha20poly1305(arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_prim_u_8_strict,
        decodeErrorData: dco_decode_s_5_error,
      ),
      constMeta: kCrateApiEncryptXchacha20Poly1305ConstMeta,
      argValues: [key, plaintext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEncryptXchacha20Poly1305ConstMeta =>
      const TaskConstMeta(
        debugName: "encrypt_xchacha20poly1305",
        argNames: ["key", "plaintext"],
      );

  @override
  String crateApiGenerateSeedPhrase() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        return wire.wire__crate__api__generate_seed_phrase();
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_s_5_error,
      ),
      constMeta: kCrateApiGenerateSeedPhraseConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGenerateSeedPhraseConstMeta => const TaskConstMeta(
        debugName: "generate_seed_phrase",
        argNames: [],
      );

  @override
  Uint8List crateApiHashBlake3({required List<int> data}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        var arg0 = cst_encode_list_prim_u_8_loose(data);
        return wire.wire__crate__api__hash_blake3(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiHashBlake3ConstMeta,
      argValues: [data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiHashBlake3ConstMeta => const TaskConstMeta(
        debugName: "hash_blake3",
        argNames: ["data"],
      );

  @override
  bool crateApiValidateSeedPhrase({required String phrase}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        var arg0 = cst_encode_String(phrase);
        return wire.wire__crate__api__validate_seed_phrase(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiValidateSeedPhraseConstMeta,
      argValues: [phrase],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiValidateSeedPhraseConstMeta => const TaskConstMeta(
        debugName: "validate_seed_phrase",
        argNames: ["phrase"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_S5Client => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_S5Client => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client;

  @protected
  S5Client
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return S5ClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  S5Client
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return S5ClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  S5Client
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return S5ClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  DirectoryListing dco_decode_directory_listing(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DirectoryListing(
      files: dco_decode_list_file_entry(arr[0]),
      directories: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  FileEntry dco_decode_file_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FileEntry(
      name: dco_decode_String(arr[0]),
      fileRefJson: dco_decode_String(arr[1]),
      size: dco_decode_u_64(arr[2]),
      mediaType: dco_decode_opt_String(arr[3]),
      timestamp: dco_decode_opt_box_autoadd_u_32(arr[4]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<FileEntry> dco_decode_list_file_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_file_entry).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  S5Error dco_decode_s_5_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return S5Error_InvalidInput(
          dco_decode_String(raw[1]),
        );
      case 1:
        return S5Error_ConnectionError(
          dco_decode_String(raw[1]),
        );
      case 2:
        return S5Error_StorageError(
          dco_decode_String(raw[1]),
        );
      case 3:
        return S5Error_FileNotFound(
          dco_decode_String(raw[1]),
        );
      case 4:
        return S5Error_CryptoError(
          dco_decode_String(raw[1]),
        );
      case 5:
        return S5Error_InternalError(
          dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  S5Keys dco_decode_s_5_keys(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return S5Keys(
      rootSecretHex: dco_decode_String(arr[0]),
      publicKeyHex: dco_decode_String(arr[1]),
      encryptionKeyHex: dco_decode_String(arr[2]),
      signingKeyHex: dco_decode_String(arr[3]),
      irohSecretKeyHex: dco_decode_String(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  S5Client
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return S5ClientImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  S5Client
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return S5ClientImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  S5Client
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return S5ClientImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  DirectoryListing sse_decode_directory_listing(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_files = sse_decode_list_file_entry(deserializer);
    var var_directories = sse_decode_list_String(deserializer);
    return DirectoryListing(files: var_files, directories: var_directories);
  }

  @protected
  FileEntry sse_decode_file_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_fileRefJson = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_mediaType = sse_decode_opt_String(deserializer);
    var var_timestamp = sse_decode_opt_box_autoadd_u_32(deserializer);
    return FileEntry(
        name: var_name,
        fileRefJson: var_fileRefJson,
        size: var_size,
        mediaType: var_mediaType,
        timestamp: var_timestamp);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<FileEntry> sse_decode_list_file_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FileEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_file_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  S5Error sse_decode_s_5_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return S5Error_InvalidInput(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return S5Error_ConnectionError(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return S5Error_StorageError(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return S5Error_FileNotFound(var_field0);
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return S5Error_CryptoError(var_field0);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return S5Error_InternalError(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  S5Keys sse_decode_s_5_keys(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rootSecretHex = sse_decode_String(deserializer);
    var var_publicKeyHex = sse_decode_String(deserializer);
    var var_encryptionKeyHex = sse_decode_String(deserializer);
    var var_signingKeyHex = sse_decode_String(deserializer);
    var var_irohSecretKeyHex = sse_decode_String(deserializer);
    return S5Keys(
        rootSecretHex: var_rootSecretHex,
        publicKeyHex: var_publicKeyHex,
        encryptionKeyHex: var_encryptionKeyHex,
        signingKeyHex: var_signingKeyHex,
        irohSecretKeyHex: var_irohSecretKeyHex);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
      S5Client raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
// ignore: invalid_use_of_internal_member
    return (raw as S5ClientImpl).frbInternalCstEncode(move: true);
  }

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
      S5Client raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
// ignore: invalid_use_of_internal_member
    return (raw as S5ClientImpl).frbInternalCstEncode(move: false);
  }

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
      S5Client raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
// ignore: invalid_use_of_internal_member
    return (raw as S5ClientImpl).frbInternalCstEncode();
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          S5Client self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as S5ClientImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          S5Client self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as S5ClientImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS5Client(
          S5Client self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as S5ClientImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_directory_listing(
      DirectoryListing self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_file_entry(self.files, serializer);
    sse_encode_list_String(self.directories, serializer);
  }

  @protected
  void sse_encode_file_entry(FileEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.fileRefJson, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_opt_String(self.mediaType, serializer);
    sse_encode_opt_box_autoadd_u_32(self.timestamp, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_file_entry(
      List<FileEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_file_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_s_5_error(S5Error self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case S5Error_InvalidInput(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case S5Error_ConnectionError(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case S5Error_StorageError(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case S5Error_FileNotFound(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case S5Error_CryptoError(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case S5Error_InternalError(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_s_5_keys(S5Keys self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.rootSecretHex, serializer);
    sse_encode_String(self.publicKeyHex, serializer);
    sse_encode_String(self.encryptionKeyHex, serializer);
    sse_encode_String(self.signingKeyHex, serializer);
    sse_encode_String(self.irohSecretKeyHex, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class S5ClientImpl extends RustOpaque implements S5Client {
  // Not to be used by end users
  S5ClientImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  S5ClientImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_S5Client,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_S5Client,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_S5ClientPtr,
  );

  /// Create a new directory.
  Future<void> createDirectory({required String path}) => RustLib.instance.api
      .crateApiS5ClientCreateDirectory(that: this, path: path);

  /// Delete a file.
  Future<void> deleteFile({required String path}) =>
      RustLib.instance.api.crateApiS5ClientDeleteFile(that: this, path: path);

  /// Disconnect from the remote node.
  Future<void> disconnect() => RustLib.instance.api.crateApiS5ClientDisconnect(
        that: this,
      );

  /// Download a raw blob by hash (no decryption).
  Future<Uint8List> downloadBlob({required String hashHex}) =>
      RustLib.instance.api
          .crateApiS5ClientDownloadBlob(that: this, hashHex: hashHex);

  /// Download a file by path (with decryption if encrypted).
  Future<Uint8List> downloadFile({required String path}) =>
      RustLib.instance.api.crateApiS5ClientDownloadFile(that: this, path: path);

  /// Check if a file exists.
  Future<bool> fileExists({required String path}) =>
      RustLib.instance.api.crateApiS5ClientFileExists(that: this, path: path);

  /// Get a file's metadata as JSON.
  Future<String?> fileGet({required String path}) =>
      RustLib.instance.api.crateApiS5ClientFileGet(that: this, path: path);

  /// Check if the client is connected.
  Future<bool> isConnected() =>
      RustLib.instance.api.crateApiS5ClientIsConnected(
        that: this,
      );

  /// List contents of a directory.
  Future<DirectoryListing> listDirectory({required String path}) =>
      RustLib.instance.api
          .crateApiS5ClientListDirectory(that: this, path: path);

  /// Get the iroh node ID for this client.
  String get nodeId => RustLib.instance.api.crateApiS5ClientNodeId(
        that: this,
      );

  /// Get the user's public key (identity).
  String get publicKey => RustLib.instance.api.crateApiS5ClientPublicKey(
        that: this,
      );

  /// Test the connection by making a simple query.
  Future<String> testConnection() =>
      RustLib.instance.api.crateApiS5ClientTestConnection(
        that: this,
      );

  /// Upload a file with encryption.
  ///
  /// Small files (< 4KB) are stored inline in directory metadata.
  /// Larger files are encrypted with XChaCha20-Poly1305 and stored separately.
  /// Returns the FileRef as JSON.
  Future<String> uploadFile(
          {required String path,
          required String filename,
          required List<int> content,
          required String mediaType}) =>
      RustLib.instance.api.crateApiS5ClientUploadFile(
          that: this,
          path: path,
          filename: filename,
          content: content,
          mediaType: mediaType);
}
